language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sumitchinchansure/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true sumitchinchansure/react-test npm run test -- --coverage

after_succes:
  - docker build -t sumitchinchansure/multi-client -f ./client
  - docker build -t sumitchinchansure/multi-nginx -f ./nginx
  - docker build -t sumitchinchansure/multi-server -f ./server
  - docker build -t sumitchinchansure/multi-worker -f ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push above images to docker hub
  - doker push sumitchinchansure/multi-client 
  - doker push sumitchinchansure/multi-nginx 
  - doker push sumitchinchansure/multi-server 
  - doker push sumitchinchansure/multi-worker