language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sumitchinchansure/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sumitchinchansure/react-test npm run test -- --coverage

after_succes:
  - docker build -t sumitchinchansure/multi-client -f ./client/Dockerfile ./client 
  - docker build -t sumitchinchansure/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t sumitchinchansure/multi-server -f ./server/Dockerfile ./server
  - docker build -t sumitchinchansure/multi-worker -f ./worker/Dockerfile ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push above images to docker hub
  - docker push sumitchinchansure/multi-client 
  - docker push sumitchinchansure/multi-nginx 
  - docker push sumitchinchansure/multi-server 
  - docker push sumitchinchansure/multi-worker